import { NombreIngrediente } from "./ingrediente";


export let listaIngredientes: { nombre: NombreIngrediente, isAlcohol: boolean, checked: boolean }[] = [
  { nombre: 'Jarabe de Azúcar', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Lima', isAlcohol: false, checked: false },
  { nombre: 'Ron Blanco', isAlcohol: true, checked: false },
  { nombre: 'Azúcar', isAlcohol: false, checked: false },
  { nombre: 'Lima', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Limón', isAlcohol: false, checked: false },
  { nombre: 'Agua con Gas', isAlcohol: false, checked: false },
  { nombre: 'Crema de Coco', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Piña', isAlcohol: false, checked: false },
  { nombre: 'Jarabe de Miel', isAlcohol: false, checked: false },
  { nombre: 'Coca-Cola', isAlcohol: false, checked: false },
  { nombre: 'Menta', isAlcohol: false, checked: false },
  { nombre: 'Ginebra', isAlcohol: true, checked: false },
  { nombre: 'Vodka', isAlcohol: true, checked: false },
  { nombre: 'Granadina', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Naranja', isAlcohol: false, checked: false },
  { nombre: 'Ron Oscuro', isAlcohol: true, checked: false },
  { nombre: 'Agua de Coco', isAlcohol: false, checked: false },
  { nombre: 'Gaseosa de Limón', isAlcohol: false, checked: false },
  { nombre: 'Limón', isAlcohol: false, checked: false },
  { nombre: 'Curaçao Azul', isAlcohol: true, checked: false },
  { nombre: 'Tequila', isAlcohol: true, checked: false },
  { nombre: 'Jägermeister', isAlcohol: true, checked: false },
  { nombre: 'Ron de Coco', isAlcohol: true, checked: false },
  { nombre: 'Mermelada de Naranja', isAlcohol: false, checked: false },
  { nombre: 'Jarabe de Arce', isAlcohol: false, checked: false },
  { nombre: 'Té Negro', isAlcohol: false, checked: false },
  { nombre: 'Soda de Agua', isAlcohol: false, checked: false },
  { nombre: 'Salsa de Tabasco', isAlcohol: false, checked: false },
  { nombre: 'Amaretto', isAlcohol: true, checked: false },
  { nombre: 'Licor de Café', isAlcohol: true, checked: false },
  { nombre: 'Helado de Vainilla', isAlcohol: false, checked: false },
  { nombre: 'Red Bull', isAlcohol: false, checked: false },
  { nombre: 'Sour Mix', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Pomelo', isAlcohol: false, checked: false },
  { nombre: 'Fanta de Limón', isAlcohol: false, checked: false },
  { nombre: 'Leche', isAlcohol: false, checked: false },
  { nombre: 'Canela', isAlcohol: false, checked: false },
  { nombre: 'Extracto de Vainilla', isAlcohol: false, checked: false },
  { nombre: 'Yema de Huevo', isAlcohol: false, checked: false },
  { nombre: 'Licor Grosella Negra', isAlcohol: true, checked: false },
  { nombre: 'Vino Tinto', isAlcohol: true, checked: false },
  { nombre: 'Whisky', isAlcohol: true, checked: false },
  { nombre: 'Licor Triple Sec', isAlcohol: true, checked: false },
  { nombre: 'Sidra de Manzana', isAlcohol: true, checked: false },
  { nombre: 'Campari', isAlcohol: true, checked: false },
  { nombre: 'Vermut Blanco', isAlcohol: true, checked: false },
  { nombre: 'Grand Marnier', isAlcohol: true, checked: false },
  { nombre: 'Jarabe de Sidra de Manzana', isAlcohol: false, checked: false },
  { nombre: 'Café', isAlcohol: false, checked: false },
  { nombre: 'Vino Blanco', isAlcohol: true, checked: false },
  { nombre: 'Absenta', isAlcohol: true, checked: false },
  { nombre: 'Albahaca', isAlcohol: false, checked: false },
  { nombre: 'Jarabe de Fresa', isAlcohol: false, checked: false },
  { nombre: 'Vermut Seco', isAlcohol: true, checked: false },
  { nombre: 'Puré de Melocotón', isAlcohol: false, checked: false },
  { nombre: 'Sirope de Horchata', isAlcohol: false, checked: false },
  { nombre: 'Aguamiel', isAlcohol: false, checked: false },
  { nombre: 'Fresa', isAlcohol: false, checked: false },
  { nombre: 'Cerveza de Jengibre', isAlcohol: true, checked: false },
  { nombre: 'Amargo de Angostura', isAlcohol: true, checked: false },
  { nombre: 'Bicarbonato de Sodio', isAlcohol: false, checked: false },
  { nombre: `Bailey's`, isAlcohol: true, checked: false },
  { nombre: 'Leche Batida', isAlcohol: false, checked: false },
]