import { NombreIngrediente } from "./ingrediente";


export let listaIngredientes: { nombre: NombreIngrediente, isAlcohol: boolean, checked: boolean }[] = [
  { nombre: 'Jarabe de Azúcar', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Lima', isAlcohol: false, checked: false },
  { nombre: 'Ron Blanco', isAlcohol: true, checked: false },
  { nombre: 'Azúcar', isAlcohol: false, checked: false },
  { nombre: 'Lima', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Limón', isAlcohol: false, checked: false },
  { nombre: 'Agua con Gas', isAlcohol: false, checked: false },
  { nombre: 'Crema de Coco', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Piña', isAlcohol: false, checked: false },
  { nombre: 'Jarabe de Miel', isAlcohol: false, checked: false },
  { nombre: 'Coca-Cola', isAlcohol: false, checked: false },
  { nombre: 'Hoja de Menta', isAlcohol: false, checked: false },
  { nombre: 'Ginebra', isAlcohol: true, checked: false },
  { nombre: 'Vodka', isAlcohol: true, checked: false },
  { nombre: 'Granadina', isAlcohol: false, checked: false },
  { nombre: 'Zumo de Naranja', isAlcohol: false, checked: false },
  { nombre: 'Ron Oscuro', isAlcohol: true, checked: false },
  { nombre: 'Agua de Coco', isAlcohol: false, checked: false },
  { nombre: 'Gaseosa de Limón', isAlcohol: false, checked: false },
  { nombre: 'Limón', isAlcohol: false, checked: false },
  { nombre: 'Curaçao Azul', isAlcohol: true, checked: false },
  { nombre: 'Tequila', isAlcohol: true, checked: false },
  { nombre: 'Jägermeister', isAlcohol: true, checked: false },
  { nombre: 'Ron de Coco', isAlcohol: true, checked: false },
  { nombre: 'Mermelada de Naranja', isAlcohol: false, checked: false },
  { nombre: 'Jarabe de Arce', isAlcohol: false, checked: false },
  { nombre: 'Té Negro', isAlcohol: false, checked: false },
  { nombre: 'Soda de Agua', isAlcohol: false, checked: false },
  { nombre: 'Salsa de Tabasco', isAlcohol: false, checked: false },
  { nombre: 'Amaretto', isAlcohol: true, checked: false },
  { nombre: 'Licor de Café', isAlcohol: true, checked: false },
  { nombre: 'Helado de Vainilla', isAlcohol: false, checked: false },
  { nombre: 'Red Bull', isAlcohol: false, checked: false },
]